trigger:
- main

pool:
  name: 'plzwork' # Your self-hosted agent pool name

steps:
  # Step 0: Disable SSL verification (temporary workaround for Git cert issue)
  - script: git config --global http.sslVerify false
    displayName: 'Disable Git SSL Verification (Not for Production Use)'

  # Step 1: Checkout the Code from GitHub
  - checkout: self
    displayName: 'Checkout Code from GitHub'

  # Step 2: Build and Run Unit Tests
  - script: mvn clean test
    displayName: 'Build and Run Unit Tests'

  # Step 3: Publish Test Results (JUnit)
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '*/target/surefire-reports/TEST-*.xml'
      testResultsFormat: 'JUnit'
      failTaskOnMissingResultsFile: true
    displayName: 'Publish Maven Test Results'

  # Step 4: Publish Build Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'target'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'
